title: "Matt Webb | Software Engineer"
description: "Software engineer specializing in developer tooling and developer experience."
baseurl: ""
url: "https://mattwebb.io"

# Build settings
markdown: kramdown
theme: null

# Syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  - .yarnrc.yml
  - .yarn
  - tsconfig.json
  - src
  - _sass
  - README.md
  - Gemfile
  - Gemfile.lock
  - .tool-versions
  - "**.ai-disclosure.md"
  - scripts

# Explicitly include built assets
include:
  - assets/js/stars.js
  - assets/css/main.css

# Site parameters
sbadges: "?longCache=true&style=for-the-badge&colorA=efefef&logo="
smallsbadges: "?longCache=true&style=for-the-badge&logo="
