name: Lint

on:
  push:
    branches: [main]
    paths:
      - '_posts/**'
  pull_request:
    branches: [main]
    paths:
      - '_posts/**'

jobs:
  lint-ai-disclosure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check AI disclosure consistency
        run: bash scripts/lint-ai-disclosure.sh
